version: '3.1'
services:
  php:
    image: php:5.6.0-apache
    container_name: kit
    ports:
      - '8001:80'

  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: colt
      MYSQL_DATABASE: kit
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - './src/mysql:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1